markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Sylinx
host: sylinx.github.com
desc: 编程创业，关注系统架构设计

custom:
    category:
        dev: 开发经验
        topic: 专题
        exp: 爱探索
        tweet: 吐槽围观
        business: 创业
    categories:
      - name:  dev
        title: 开发经验

      - name:  topic
        title: 专题

      - name:  exp
        title: 爱探索

      - name:  business
        title: 创业

      - name:  tweet
        title: 吐槽围观

meta:
    author:
        name: Sylinx
        email: sylinxsoft@gmail.com
        disqus: sylinx              # Disqus缩略标识
        gcse: 006133068628824591854:vbkpwqtvl3e     # Google自定义搜索标识ID
        github: sylinx                # GitHub账号
        gravatar: 0138b33d806287a9b61ebdba22a1f82e  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
